### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by michaelmior** [peterhurford/git-it-on.zsh#28]
It would be nice if this used HTTPS instead of HTTP.

**Comment by peterhurford** [comment]
:+1:

**Comment by peterhurford** [comment]
@michaelmior Closed because GitHub autoforwards HTTP to HTTPS now?

**Comment by michaelmior** [comment]
Closed because there was no response and I was trying to clear my issues
list. This would still be ideal because forwarding to HTTPS removes most of
the security benefits.

**Comment by peterhurford** [comment]
@michaelmior Review https://github.com/peterhurford/git-it-on.zsh/pull/36?

**Comment by michaelmior** [comment]
Looks good to me, although I haven't had the chance to test it. Thanks!
