### ISSUE TITLE
slight error in bash

### ISSUE THREAD

**Issue by iveksl2** [peterhurford/git-it-on.zsh#37]
When on a branch

`mbookpro001-554:data-insights igorveksler$ gitit .  
bash: 1+${#$(git rev-parse --show-toplevel)}: bad substitution  
bash: echo: write error: Broken pipe`

I am soon switching to zshell thought but so your aware :)

**Comment by peterhurford** [comment]
Thanks!  I need to figure out a testing framework for bash + zsh.

**Comment by iveksl2** [comment]
I am now on zsh so i dont care

**Comment by peterhurford** [comment]
Re-filed as https://github.com/peterhurford/git-it-on.zsh/issues/38
