### ISSUE TITLE
Gitlab domain name changed to httpslab

### ISSUE THREAD

**Issue by uipo78** [peterhurford/git-it-on.zsh#48]
pretty sure the fix is to add something like this a line or two [hereunder](https://github.com/peterhurford/git-it-on.zsh/blob/master/git-it-on.plugin.zsh#L40):

```bash
url="${url/httpslab/gitlab}"
```

lemme know if you'd like me to submit a pr :D

**Comment by peterhurford** [comment]
This sounds reasonable. A PR would be grand. Thanks! Do you have any Gitlab repos and would you be able to test?

**Comment by alichtman** [comment]
I just ran into this same issue. Any idea when this will be fixed?

**Comment by peterhurford** [comment]
I don't intend to fix this myself but I'd happily accept a PR

**Comment by alichtman** [comment]
No worries. I’ll fix it next time it really annoys me (and I somehow manage to clear my never ending todo list)
